# Generated by Django 5.2.4 on 2025-07-28 08:01

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=user.models._upload_user_avatar, verbose_name='Avatar'),
        ),
    ]
