# Generated by Django 5.2.4 on 2025-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codespace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codespace',
            name='id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
