# Generated by Django 5.2.4 on 2025-07-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codespace', '0002_alter_codespace_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codespace',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
