# Generated by Django 5.2.4 on 2025-07-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codespace', '0003_codespace_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codespace',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
