# Generated by Django 5.2.4 on 2025-07-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codespace', '0004_alter_codespace_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='codespace',
            name='version',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
