# Generated by Django 5.2.4 on 2025-07-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codespace', '0005_codespace_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='syntax',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='syntax',
            name='extension',
            field=models.CharField(default=1, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='syntax',
            unique_together={('title', 'status', 'extension')},
        ),
    ]
