# Generated by Django 5.2.4 on 2025-07-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codespace', '0006_alter_syntax_unique_together_syntax_extension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='syntax',
            name='content_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
